config/routes.rb
Rails.application.routes.draw do

  resources :projects
  resources :tasks
  resources :users

   root 'welcome#home'

   get 'faq' => 'welcome#faq'

   get 'home' => 'welcome#home'

   get 'terms' => 'welcome#terms'

   get 'about' => 'welcome#about'

   get 'tasks' => 'tasks#index'

end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :project
  belongs_to :role
  belongs_to :user

  def already_exists
    if Membership.where(project_id:project_id,user_id:user_id).length > 0 && !self.id
      errors.add(:user_id, "This membership already exists")
    end
  end


end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks
  has_many :memberships
  has_many :users, through: :memberships
  validates :name, presence: true
end

app/models/role.rb
class Role < ActiveRecordbase
  has_many :projects, through: :memberships
  has_many :memberships
end

app/models/task.rb
class Task < ActiveRecord::Base
  validate :date_cannot_be_in_the_past
  validates :date, presence: true
  validates :description, presence: true
  belongs_to :project

  private
  def date_cannot_be_in_the_past
    if date.present? && date < Date.today
      errors.add(:date, "can't be in the past")
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :first_name, :last_name, :email, presence: true
  validates :email, uniqueness: true
  has_secure_password

  has_many :projects, through: :memberships
  has_many :memberships

  def full_name
    "#{first_name} #{last_name}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController


def index
  @tasks = Task.all
end


def new
   @task = Task.new
end
def create
  @task = Task.new(task_params)
  @task.save
  if @task.save
    redirect_to tasks_path
  else
    render :new
  end

end

def edit
  @task = Task.find(params[:id])
end


def update
  @task = Task.find(params[:id])
  if @task.update(task_params)
  redirect_to @task, notice: "You have succesfully edited your task"
  else
  render :new
  end

end



def destroy
  @task = Task.find(params[:id])
  @task.destroy
  redirect_to tasks_url, notice: 'Task was succesfully deleted '
end

def show
  @task = Task.find(params[:id])


end




private

def task_params

  params.require(:task).permit{
    :description
    :date
    :completed
  }
end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
def new
  @user = User.new

end

def create
  @user = User.new(user_params)
  @user.save
  if @user.save
    redirect_to root_path
  else
    render :new
  end
end

def show
  @user = User.find(params[:id])
end

def edit
  @user = User.find(params[:id])
  redirect_to users_path

end

def destroy
  @user = User.find(params[:id])
  @user.destroy
  redirect_to users_path notice: "User was succesfully destroyed"

end

def update
  @user = User.find(params[:id])
  if @user.update(user_params)
    redirect_to users_path  notice: "User"
  else
  end
end
private



def user_params
  params.require(:user).permit{
    :first_name
    :last_name
    :email
  }


end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
    @quotesncharacters = [
      "Failure is not an option. Everyone has to Succeed", "Arnold Shwarznegger",
      "Your time is limited so don't waste it living someone elses life", "Steve Jobs",
      "Better Ingredients, Better Pizza","Papa Johns"]


  end
  def terms

  end

  def faq
    @faq = ["What do I do if I have a problem?", "Well if you have a problem come to me ","But what if I'm nerrrrrvousssss..", "No choice dude, you're answering my questions" ]

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>
    <title>gCamp</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <%= link_to 'gCamp','/', class:'navbar-brand' %>
        </div>
    </nav>
    <div class="container">
      <%= yield %>
      <footer class="site-footer col-md-12">
        <%= link_to 'About', 'about', class:'navbar-brand' %>
         <%= link_to 'Terms', 'terms', class:'navbar-brand' %>
         <%= link_to 'FAQ', 'faq', class:'navbar-brand' %>
          <%= link_to 'Projects', projects_path, class:'navbar-brand' %>
          <%= link_to 'Tasks', tasks_path, class:'navbar-brand' %>
           <%= link_to 'Users', users_path, class:'navbar-brand' %>
      </footer>
    </div>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <%= form_for(@project, html:{class:'form-horizontal col-md-12'}) do |f| %>
  <div class="form-group">
    <%= f.label "Name", class:'col-md-2 control-label' %>
    <div class="col-md-4">
      <%= f.text_field :name, class:'form-control' %>
    </div>
  </div>
  <div class="actions col-md-offset-2">
    <%= f.submit  class:'btn btn-primary' %>
    <%= link_to 'Cancel', projects_path, class:'btn btn-default' %>
  </div>
  <% end %>

app/views/projects/edit.html.erb
<div class="page-header">
  <h1>Edit Project</h1>
</div>
<%= render 'form' %>

app/views/projects/index.html.erb
<% if notice %>
<div class="alert alert-success text-center"><%= notice %></div>
<% end %>

<div class="page-header">
  <div class="pull-right"><%= link_to 'New Project', new_project_path, class:'btn btn-primary' %></div>
  <h1>Projects</h1>
</div>
<table class="table">
  <thead>
    <th>Name</th>
    <!-- <th>Members</th> -->
    <th>Tasks</th>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
    <tr>
      <td><%= link_to project.name, project %></td>
      <td><%= link_to "#{project.tasks.size}", project_tasks_path(project) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/projects/new.html.erb
<div class="page-header">
  <h1>Create Project</h1>
</div>
<%= render 'form' %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/tasks/_form.html.erb
<% if @task.errors.any? %>
<div id="error_explanation" class="alert alert-danger col-md-offset-1 col-md-6 black-color">
  <h4><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h4>
  <ul>
    <% @task.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<%= form_for(@task, html:{class:'form-horizontal col-md-12'}) do |f| %>
  <div class="form-group">
    <%= f.label :description, class:'col-md-1 control-label' %>
    <div class="col-md-4">
      <%= f.text_field :description, class:'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label "Due Date", class:'col-md-1 control-label' %>
    <div class="col-md-4">
      <%= f.date_field :date, class:'form-control' %>
    </div>
  </div>
  <% if params[:action] == "edit" %>
    <div class="checkbox">
      <label class="col-md-4 col-md-offset-1">
        <%= f.check_box :completed %>
        Complete
      </label>
    </div>
  <% end %>
  <div class="actions col-md-offset-1">
    <%= f.submit class:'btn btn-primary' %>
    <%= link_to 'Cancel', tasks_path, class:'btn btn-default' %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1 class="page-header">Edit Task</h1>
<%= render 'form' %>

app/views/tasks/index.html.erb
<div class="page-header">
  <div class="pull-right">
    <%= link_to 'New Task', new_task_path, class:"btn btn-primary" %>
  </div>
  <div class="pull-right filter">
    <% if params[:type] == "incomplete" %>
      <%= link_to 'All', type:'all' %> | Incomplete
    <% else %>
      All | <%= link_to 'Incomplete', type:'incomplete' %>
    <% end %>
  </div>
  <h1>Tasks</h1>
</div>
<table class="table">
  <thead>
    <tr>
      <th>Description</th>
      <th>Complete</th>
      <th>Due</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <% if task.date.class == Date && task.date <= Date.today+7 && task.complete == false %>
        <tr class="red">
      <% else %>
        <tr>
      <% end %>
        <td>
          <%= task.description %>
        </td>
        <td>
          <%= task.completed %>
        </td>
        <td>
          <%= task.date %>
        </td>
        <td class="pull-right">
          <%= link_to 'Show', task, class:"btn btn-success" %>
          <%= link_to 'Edit', edit_task_path(task), class:"btn btn-primary" %>
          <%= link_to 'Delete', task, method: :delete, data: { confirm: 'Are you really sure?' }, class:"btn btn-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/tasks/new.html.erb
<h1 class="page-header">New Task</h1>

<%= render "form" %>

app/views/tasks/show.html.erb
<% if notice %>
  <div class="alert alert-success text-center"><%= notice %></div>
<% end %>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>
<p>
  <strong>Due Date:</strong>
  <%= @task.date %>
</p>
<p>
  <strong>Complete:</strong>
  <%= @task.completed %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
<div id="error_explanation" class="alert alert-danger col-md-offset-1 col-md-6 color-black">
  <h4><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h4>

  <ul>
    <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>


<%= form_for(@user, html:{class:'form-horizontal col-md-12'}) do |f| %>
<div class="form-group">
  <%= f.label :first_name, class:'col-md-1 control-label' %>
  <div class="col-md-4">
    <%= f.text_field :first_name, class:'form-control' %>
  </div>
</div>
<div class="form-group">
  <%= f.label :last_name, class:'col-md-1 control-label' %>
  <div class="col-md-4">
    <%= f.text_field :last_name, class:'form-control' %>
  </div>
</div>
<div class="form-group">
  <%= f.label :email, class:'col-md-1 control-label' %>
  <div class="col-md-4">
    <%= f.email_field :email, class:'form-control' %>
  </div>
</div>
<div class="form-group">
  <%= f.label :password, class:'col-md-2 control-label' %>
  <div class="col-md-4">
    <%= f.password_field :password, class:'form-control' %>
  </div>
</div>
<div class="form-group">
  <%= f.label :password_confirmation, class:'col-md-2 control-label' %>
  <div class="col-md-4">
    <%= f.password_field :password_confirmation, class:'form-control' %>
  </div>
<div class="actions col-md-offset-1">
  <%= f.submit class:'btn btn-primary' %>
  <%= link_to 'Cancel', users_path, class:'btn btn-default' %>
</div>
<div class="well col-md-4 col-md-offset-1" style="position: inherit;">
  <%= link_to 'Delete User', @user, class:'btn btn-danger col-md-4 col-md-offset-4', title:'button well', method: :delete, data: { confirm: 'Are you sure?' } %>
</div>
<% end %>

app/views/users/edit.html.erb
<h1 class="page-header">Edit User</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<% if notice %>
<div class="alert alert-success text-center"><%= notice %></div>
<% end %>
<div class="page-header">
  <div class="pull-right">
    <%= link_to 'New User', new_user_path, class:"btn btn-info" %>
  </div>
  <h1>Users</h1>
</div>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= link_to "#{user.first_name} #{user.last_name}", user_path(user) %></td>
      <td><%= mail_to user.email %></td>
      <td class="text-right"><%= link_to 'Edit', edit_user_path(user) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1 class="page-header">Sign Up</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<% if notice %>
  <div class="alert alert-success text-center"><%= notice %></div>
<% end %>

<div class="page-header">
  <div class="pull-right">
    <%= link_to 'Edit', edit_user_path, class:'btn btn-primary' %>
  </div>
  <h2><%= "#{@user.first_name} #{@user.last_name}" %></h2>
</div>
<dl class="dl-horizontal">
  <dt>First Name</dt>
  <dd><%= @user.first_name %></dd>
  <dt>Last Name</dt>
  <dd><%= @user.last_name %></dd>
  <dt>Email</dt>
  <dd><%= mail_to @user.email %></dd>
</dl>
</div>

app/views/welcome/about.html.erb
<h1>About</h1>
<div class="row">
  <%= image_tag '1.JPG', class:'col-md-4 img-rounded', style:'margin:0' %>
  <div class="col-md-8">
    <p> Essentially we are entiatly a construct of being formed in the bowels of Chronus for one purpose/... Ruling the land of Olympus.  We wake up in the middle of the night and furiously write down ideas about how you make your online life better.</p>
    <p>When we're not hard at work, we're hard at play - we're the loud ones in the bar, and we're always the ones shutting the place down.  Human communication and collaboration is what drives us, and it infuses every feature of gCamp.</p>
  </div>
</div>

app/views/welcome/faq.html.erb
<h1>Frequently Asked Questions</h1>
<div class="faq">
    <% @faq.each do |question| %>
      <h4><%= question[0] %></h4>
      <p>
        <%= question[1] %>
      </p>
    <% end %>
</div>

app/views/welcome/home.html.erb
<div class="jumbotron">
  <h1>gCamp</h1>
  <p style="margin-top: 25px">Your life, organized.</p>
</div>
<div class="row">
  <div class="col-md-4">
    <%= image_tag '1.jpg', class:'img-rounded img-responsive' %>
    <div class="panel panel-primary">
      <div class="panel-heading">Tasks</div>
      <div class="panel-body homePanel">Grouped by projects and lists. Just the way you like 'em.</div>
    </div>
  </div>
  <div class="col-md-4">
    <%= image_tag '2.jpg', class:'img-rounded img-responsive' %>
    <div class="panel panel-primary">
      <div class="panel-heading">Documents</div>
      <div class="panel-body homePanel">
        <ul>
          <li>Upload</li>
          <li>Comment</li>
          <li>Reverse</li>
        </ul>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <%= image_tag '3.jpg', class:'img-rounded img-responsive' %>
    <div class="panel panel-primary">
      <div class="panel-heading">Comments</div>
      <div class="panel-body homePanel">
        <ul>
          <li>Comment on tasks and documents.</li>
          <li>Get email notifications</li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="container">
<% @quotesncharacters.each_with_index do |text,i|  %>

<% if i.even? %>
<dt> "<%= text %>"" </dt>
<% else %>
<dd class="text-muted"> -<%= text %>  </dd>
<br>
<% end %>
<% end %>
</div>


<hr>

app/views/welcome/terms.html.erb
<head>
  <style media="screen">
   p {
     align:
   }
  </style>
</head>


<body>

  <h2> Terms </h2>

  <div class="container">

    Registration and security
    You must be over eighteen years of age to register on our website and must ensure that the details provided by you on registration are true, accurate, current and complete. It is your responsibility to update and inform us of any changes to the details provided on registration. Although certain parts of our website may be used by anyone who visits without requiring registration, some of the Services require you to register in order to enable us to verify your identity.

    By registering with the service, you agree that we can send you emails about your account, other PrimeLocation services and occasional third party offers. You can manage your communication preferences or unsubscribe from communications at any time via the myPrimeLocation section of the website.

    When registering, you will be asked to create a password and will be responsible for maintaining the confidentiality of your password and restricting access to your computer, as you will be accountable for any activities conducted under your password. If you believe that someone has accessed your account without authorisation, please contact us immediately.

    Materials you provide
    By submitting content on our website or otherwise providing content to us in connection with the Services ('Materials'), you grant us a royalty-free, perpetual, irrevocable and non-exclusive right and license to (a) use, reproduce, distribute, display, modify and edit these Materials in connection with the Services and (b) sublicense these rights. We will not pay you any fees for these Materials and reserve the right in our sole discretion to remove or edit them at any time. You also warrant and represent that you have all rights necessary to grant us these rights. We permit you to post Materials on our website in accordance with our procedures provided that the content is not illegal, obscene, abusive, threatening, defamatory or otherwise objectionable to us.

    Your responsibilities
    We are not an estate agency and we provide a service whereby agents may market and you may view property details ('Details') together with other content hosted and developed by us. Agents are responsible for preparing the Details and fielding enquiries directly from you. We do not get involved in any communications between you and agents and we do not participate in any part of the transaction.

    Details are hosted by us in good faith but are produced directly by agents and have not been verified by us. You are responsible for making your own enquiries and we provide no guarantee and accept no responsibility for the accuracy or completeness of any information contained within the Details.

    You are responsible for checking, confirming and satisfying yourself as to the accuracy of any Details.
    You are responsible for instructing a surveyor and obtaining legal advice before committing to any purchase.
    You are responsible for ensuring that you act in good faith towards any other parties.
    Availability of website
    We strive to ensure that our website and the Services are available to you at all times but cannot guarantee that either the website or the Services will operate continuously, without interruptions or be fault free. On occasion, necessary maintenance or upgrade work requires us to make the website and the Services unavailable without notice, but we aim to keep downtime to a minimum. We accept no liability for any interruption or loss of service. We reserve the absolute right to alter, suspend or discontinue any part of our website or the Services, including your access to it.

  </div>

</body>